.TH MY_SHELL Manual
.SH NAME
my_shell \- Simple shell program

.SH SYNOPSIS
.B my_shell

.SH DESCRIPTION
My Shell is a simple shell program that reads commands from the user, tokenizes them, and executes the commands.

.SH COMMANDS
.TP
.B exit 
Exit the shell.

.TP
.B alt + D
Close the prompt.

.TP
.B ls
Lists contents.

.SH INTERACTIVE MODE
If run interactively, the shell will display a prompt "($) " and wait for user input. It will then execute the entered command.

.SH NON-INTERACTIVE MODE
The shell returns 0 upon succesful exection and non-zero if there is an error.

.SH EXAMPLES
.PP
.B my_shell
Run the shell interactively

.PP
.B my_shell < script.txt
Run the shell non-interactively using a script file.

.SH SEE ALSO
List any related commands or resources.

.SH AUTHOR
Jonathan Perez
jonathanperez9743@gmail.com

Osvaldo Antompietri
antompietriosvaldo@gmail.com
